(IAC-480) Update to handle new SAS_CERTIFICATE_GENERATOR default.
sassoftware/viya4-deployment pull request #211
Opened 2022-04-18 19:28 UTC by jarpat

# Changes
Update the `customer-provided-merge-sas-certframe-configmap.yaml` jinja template to handle the new default value for `SAS_CERTIFICATE_GENERATOR` starting in 2021.2.6.
This change makes it so that `SAS_CERTIFICATE_GENERATOR` is set based off the value the user defines for `V4_CFG_TLS_GENERATOR`, rather than falling back to the default.

# Tests
1. Performed a 2021.2.6 deployment in a 1.22.6 AKS Cluster. Set `V4_CFG_TLS_GENERATOR:cert-manager` and the resulting deployment was successful. Cert-manager was used as the cert generator.
2. Performed a 2021.2.6 deployment in a 1.22.6 AKS Cluster. Set `V4_CFG_TLS_GENERATOR:openssl` as well as the required  variables `V4_CFG_TLS_CERT, V4_CFG_TLS_KEY, V4_CFG_TLS_TRUSTED_CA_CERTS` and the resulting deployment was successful. openssl was used as the cert generator.

Note: Documentation coming in a separate ticket.

2022-04-18 19:30 UTC, thpang requested changes
One small change.

2022-04-18 19:30 UTC, thpang commented on roles/vdm/templates/generators/customer-provided-merge-sas-certframe-configmap.yaml
> +{% elif V4_CFG_TLS_GENERATOR == "cert-manager"%}
I would add a space between the " and the } at the end of this line.

2022-04-18 19:37 UTC, thpang approved these changes
LGTM

2022-04-19 21:44 UTC, sayeun approved these changes
👍

2022-04-19 21:45 UTC, merged