(IAC-581) V4_CFG_TLS_TRUSTED_CA_CERTS is required for TLS enabled Viya on AWS clusters
sassoftware/viya4-deployment pull request #251
Opened 2022-07-05 22:08 UTC by dhoucgitter

Issue Description: When deploying Viya4 to IAC created AWS clusters (in particular those using the sassoftware/viya4-iac-aws software to create the cluster), and when either full-stack or front-door TLS is configured for the deployment, it is mandatory that a value be set for the configuration variable V4_CFG_TLS_TRUSTED_CA_CERTS.

2022-07-06 13:40 UTC, dhoucgitter commented
When I was working on development tests for verifying the logging and monitoring behavior for the OpenSearch update last sprint, I was unable to get the AWS TLS enabled Viya deployment to stabilize. You and I had a chat about the certificate oriented log messages that I noticed in the pods having trouble which led to our discussion that for AWS deployed clusters that have TLS enabled, it was necessary to provide a certificate bundle that contains both the intermediate and root certificates for all AWS Regions obtained from AWS [here](https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/UsingWithRDS.SSL.html) by pointing to them using the V4_CFG_TLS_TRUSTED_CA_CERTS configuration variable. Once I did that, the pods that were failing started as expected.

2022-07-06 14:07 UTC, AWSmith0216 commented
Were you using an external DB provisioned in AWS?

2022-07-06 14:37 UTC, dhoucgitter commented
> Were you using an external DB provisioned in AWS?

Yes, I was allowing IAC to provision an external postgres DB, both in AWS and in Azure.

2022-07-06 15:00 UTC, thpang commented
For AWS the certs are needed for the external postgres server; however, I don't believe they are needed if you use the internal database. So that's the focus of my question why are they needed? We document the scenario where the external postgres server needs a cert.

2022-07-06 18:35 UTC, thpang requested changes
Need clarity.

2022-07-06 18:35 UTC, thpang commented on docs/CONFIG-VARS.md
> +| V4_CFG_TLS_TRUSTED_CA_CERTS | Path to directory containing only PEM encoded trusted CA certificates files | string | | false | Required when V4_CFG_TLS_MODE is set to full-stack or front-door and t
This is even more confusing. Simply state if you're using an external database that has TLS enabled one must add the PEM cert file to this location. This applies to Open Source K8s, any 3rd party Postgres Server. Either list exceptions here as a table or something. I believe Azure and GCP work fine with an external database but AWS does not. Same with Open Source as stated earlier.

2022-07-07 21:00 UTC, thpang commented
I looked at this yesterday. The table and text just seem to be there, no description. I would just rather have text in the note that says when using an external database on AWS/Open Source please refer to this doc. And then have a doc that outlines what to do in terms of using AWS and Open Source showing how where to get the files and copy those into the correct location. I believe somewhere we have this in the docs, but don't know where.

2022-08-02 16:53 UTC, thpang approved these changes
LGTM

2022-08-02 19:07 UTC, jarpat commented on docs/user/TrustedCACerts.md
> +Need some advice here, Thomas are you able to provide what's required here?
```suggestion
If performing a Viya 4 deployment against Opensource Kubernetes whose infrastructure was created with the [viya4-iac-k8s](https://github.com/sassoftware/viya4-iac-k8s) project, and you want to get the certificates for the external Postgres database, follow the steps in the "notes" section in the [documentation here](https://github.com/sassoftware/viya4-iac-k8s/blob/main/docs/CONFIG-VARS.md#postgresql-server). You will have the option to either use the system default certificates in which case they will be copied to your workspace for use, or you can provide your own generated certificates.

```

2022-08-02 19:35 UTC, jarpat commented on docs/CONFIG-VARS.md
> +| :--- | ---: | ---: | ---: | ---: | ---: | ---: |
Lines 191-198 are duplicated.
```suggestion
```

2022-08-02 19:40 UTC, dhoucgitter commented on docs/CONFIG-VARS.md
> +| :--- | ---: | ---: | ---: | ---: | ---: | ---: |
Good catch.

2022-08-02 19:41 UTC, jarpat approved these changes

2022-08-02 19:57 UTC, thpang approved these changes
LGTM

2022-08-02 21:16 UTC, merged