feat: (IAC-842) Add V4_CFG_CERTS and conditionally download viya4-orders-cli
sassoftware/viya4-deployment pull request #383
Opened 2023-01-31 19:24 UTC by jarpat

### Changes
* Added `V4_CFG_CERTS` to allow the user to define a path to a pre-downloaded certificates file
* The viya4-orders-cli is now conditionally downloaded during ansible execution 
  * If the user defines `V4_CFG_LICENSE`, `V4_CFG_CERTS`,  & `V4_CFG_DEPLOYMENT_ASSETS` the CLI is no longer installed since we already have all the required files on disk.

### Tests

**WIP**

2023-02-01 21:49 UTC, riragh requested changes

2023-02-01 21:49 UTC, riragh commented on docs/CONFIG-VARS.md
> +| V4_CFG_LICENSE | Path to pre-downloaded license file | string | | false| Leave blank to download the [license file](https://go.documentation.sas.com/doc/en/sasadmincdc/v_036/itopscon/n08bpieatgmfd8
Need to update "v_036" to default

2023-02-01 21:49 UTC, riragh commented on docs/CONFIG-VARS.md
> +| V4_CFG_CERTS | Path to pre-downloaded certificates file | string | | false| Leave blank to download the [certificates file](https://go.documentation.sas.com/doc/en/sasadmincdc/v_036/itopscon/n08bpi
same as above.

2023-02-01 21:58 UTC, jarpat commented on docs/CONFIG-VARS.md
> +| V4_CFG_LICENSE | Path to pre-downloaded license file | string | | false| Leave blank to download the [license file](https://go.documentation.sas.com/doc/en/sasadmincdc/v_036/itopscon/n08bpieatgmfd8
Good catch, doc changes made.

2023-02-01 22:00 UTC, riragh approved these changes
LGTM

2023-02-01 22:36 UTC, anthoday approved these changes

2023-02-02 14:05 UTC, dhoucgitter approved these changes

2023-02-07 21:36 UTC, thpang approved these changes
LGTM

2023-02-08 16:53 UTC, merged