docs: (IAC-894) Add troubleshoot documentation around docker requirements.
sassoftware/viya4-deployment pull request #384
Opened 2023-02-03 20:44 UTC by jarpat

### Changes
Adds troubleshooting documentation around Docker requirements when you are running this project directly on your host rather than using the docker container.

As of [release 6.0.0](https://github.com/sassoftware/viya4-deployment/releases/tag/6.0.0), it's required that if you are running this project using Ansible directly on your workstation, it needs Docker to be installed and the executing user should be able to access it. This is so that we can consume the [sas-orchestration tool](https://go.documentation.sas.com/doc/en/itopscdc/default/dplyml0phy0dkr/p0nid9gu3x2cvln1pzpcxa68tpom.htm#p1garxk7w4avg2n1hd6e4nt5kks7), which is available as a Docker image to generate the [SASDeployment Custom Resource file](https://go.documentation.sas.com/doc/en/itopscdc/default/dplyml0phy0dkr/p0nid9gu3x2cvln1pzpcxa68tpom.htm#p012wq5dhcqbx8n12abyqe25m4nu)

So this extra doc will help users who run into a failures around this missing dep.

2023-02-03 20:51 UTC, riragh approved these changes

2023-02-03 20:55 UTC, thpang approved these changes
LGTM

2023-02-03 21:07 UTC, anthoday approved these changes

2023-02-03 21:38 UTC, dhoucgitter approved these changes

2023-02-03 22:26 UTC, sayeun requested changes
see **the** [**official** ...]

2023-02-06 15:01 UTC, jarpat commented
> see **the** [**official** ...]

@sayeun, changes made, ready for re-review.

2023-02-07 16:16 UTC, sayeun approved these changes

2023-02-07 16:17 UTC, merged