feat: iac-320 Provide context based routing option for Logging and Monitoring
sassoftware/viya4-deployment pull request #386
Opened 2023-02-06 22:12 UTC by dhoucgitter

WIP

### Changes

By default, viya4-deployment supports deploying sassoftware/viya4-monitoring-kubernetes using host-based routing for the logging and monitoring applications. Following a successful host-based routing deployment of cluster-logging and cluster-monitoring, OpenSearch dashboards can be accessed at dashboards.cluster.host.example.com and grafana can be accessed at grafana.cluster.host.example.com

This pull request adds support to viya4-monitoring for deploying sassoftware/viya4-monitoring-kubernetes with path-based routing. Following a successful path-based routing deployment of cluster-logging and cluster-monitoring, OpenSearch dashboards can be accessed at cluster.host.example.com/dashboards and grafana can be accessed at cluster.host.example.com/grafana
- Add a new V4M ansible-vars configuration parameter V4M_ROUTING. Supported values for V4M_ROUTING are `host-based`, which is the default, and `path-based`.
- Add a validation task to ensure that `host-based` and `path-based` are the only acceptable values for V4M_ROUTING.
- Always use the same V4M_ROUTING option to install cluster-logging and cluster-monitoring when installing them separately.

### Testing

Development tests executed against V4M stable branch using OpenSearch 1.x

| Scenario | Task | Provider | K8s | V4_CFG_BASE_DOMAIN | V4M_BASE_DOMAIN | V4M_ROUTING | DAC tags | V4M ingress result |
|--|--|--|--|--|--|--|--|--|
| 1 | Install cluster-logging | Azure | 1.24.6 | dhmonlog.devops.unx.sas.com | dhmonlog.devops.unx.sas.com | not specified | cluster-logging,install | As expected, host-based ingress URL type, the default is used. Dashboards available at dashboards.dhmonlog.devops.unx.sas.com, OpenSearch available at search.dhmonlog.devops.unx.sas.com |
| 2 | Install cluster-logging with invalid V4M_ROUTING | Azure | 1.24.6 | dhmonlog.devops.unx.sas.com | dhmonlog.devops.unx.sas.com | nodeport | cluster-logging,install | DAC exits with the following validation error since nodeport is not a supported value for V4M_ROUTING: "msg": "Invalid V4M_ROUTING value: nodeport\nSupported values for V4M_ROUTING are `host-based` or `path-based`\n"
| 3 | Install cluster-logging | Azure | 1.24.6 | dhmonlog.devops.unx.sas.com | dhmonlog.devops.unx.sas.com | host-based | cluster-logging,install | The specified host-based ingress URL type is used. Dashboards available at dashboards.dhmonlog.devops.unx.sas.com, OpenSearch available at search.dhmonlog.devops.unx.sas.com |
| 4 | Install cluster-logging | Azure | 1.24.6 | dhmonlog.devops.unx.sas.com | dhmonlog.devops.unx.sas.com | path-based | cluster-logging,install | The specified path-based ingress URL type is used. Dashboards available at dhmonlog.devops.unx.sas.com/dashboards, OpenSearch available at dhmonlog.devops.unx.sas.com/search |
| 5 | Install cluster-monitoring | Azure | 1.24.6 | dhmonlog.devops.unx.sas.com | dhmonlog.devops.unx.sas.com | not specified | cluster-monitoring,install | As expected, host-based ingress URL type, the default is used. Monitoring apps available at grafana.dhmonlog.devops.unx.sas.com,prometheus.dhmonlog.devops.unx.sas.com, and alertmanager.dhmonlog.devops.unx.sas.com |
| 6 | Install cluster-monitoring | Azure | 1.24.6 | dhmonlog.devops.unx.sas.com | dhmonlog.devops.unx.sas.com | path-based | cluster-monitoring,install | The specified path-based ingress URL type is used. Monitoring apps available at dhmonlog.devops.unx.sas.com/grafana,dhmonlog.devops.unx.sas.com/prometheus, and dhmonlog.devops.unx.sas.com/alertmanager |
| 7 | Install cluster-logging,cluster-monitoring | Azure | 1.24.6 | dhmonlog.devops.unx.sas.com | dhmonlog.devops.unx.sas.com | host-based | cluster-logging,cluster-monitoring,install | The specified host-based ingress URL type is used. Dashboards available at dashboards.dhmonlog.devops.unx.sas.com, OpenSearch available at search.dhmonlog.devops.unx.sas.com, Monitoring apps available at grafana.dhmonlog.devops.unx.sas.com,prometheus.dhmonlog.devops.unx.sas.com, and alertmanager.dhmonlog.devops.unx.sas.com  |

2023-03-17 18:31 UTC, thpang requested changes
Be sure to look through the monitoring/logging section to clean up any extra files left over that used to support `host-based` deployments. These probably live in a new directory.

2023-03-17 19:59 UTC, dhoucgitter commented
> Be sure to look through the monitoring/logging section to clean up any extra files left over that used to support `host-based` deployments. These probably live in a new directory.

Identified a set of files to remove, re-running monitoring and logging uninstall/install cycle to confirm those deletions are good.

2023-03-20 17:30 UTC, jarpat approved these changes

2023-03-23 18:45 UTC, thpang approved these changes

2023-03-23 20:02 UTC, merged